### ISSUE TITLE
when typing /ooc (message) we get an internal error

### ISSUE THREAD

**Issue by aerysaegis** [McCrearyD/Caeda_Engine#13]
Error as seen in console:

17.03 09:45:08 [Server] ERROR null
17.03 09:45:08 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ooc' in plugin Caeda_Engine v1.1
17.03 09:45:08 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
17.03 09:45:08 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
17.03 09:45:08 [Server] INFO Caused by: java.lang.NullPointerException
17.03 09:45:08 [Server] INFO at com.dyllansplugins.caeda.engine.chat.ChatUtils.sendOOCMessage(ChatUtils.java:91) ~[?:?]
17.03 09:45:08 [Server] INFO at com.dyllansplugins.caeda.engine.commands.Chat.onCommand(Chat.java:76) ~[?:?]
17.03 09:45:08 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
17.03 09:45:08 [Server] INFO ... 15 more

**Comment by McCrearyD** [comment]
Internal error fixed, but functionality was removed (temporarily)
