### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by aerysaegis** [McCrearyD/Caeda_Engine#2]
25.02 20:49:52 [Server] ERROR Could not pass event PlayerJoinEvent to Caeda_Engine v1.1
25.02 20:49:52 [Server] INFO org.bukkit.event.EventException
25.02 20:49:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
25.02 20:49:52 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: " but not above a good prank."
25.02 20:49:52 [Server] INFO at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_161]
25.02 20:49:52 [Server] INFO at java.lang.Integer.parseInt(Integer.java:569) ~[?:1.8.0_161]
25.02 20:49:52 [Server] INFO at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_161]
25.02 20:49:52 [Server] INFO at com.dyllansplugins.caeda.engine.player.CharacterCard.fromString(CharacterCard.java:332) ~[?:?]
25.02 20:49:52 [Server] INFO at com.dyllansplugins.caeda.engine.player.CharacterCard.fromString(CharacterCard.java:392) ~[?:?]
25.02 20:49:52 [Server] INFO at com.dyllansplugins.caeda.engine.main.CaedaEngine.loadPlayer(CaedaEngine.java:523) ~[?:?]
25.02 20:49:52 [Server] INFO at com.dyllansplugins.caeda.engine.main.CaedaEngine.loadPlayer(CaedaEngine.java:535) ~[?:?]
25.02 20:49:52 [Server] INFO at com.dyllansplugins.caeda.engine.events.PlayerLogListener.onPlayerLogin(PlayerLogListener.java:22) ~[?:?]
25.02 20:49:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
25.02 20:49:52 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
25.02 20:49:52 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
25.02 20:49:52 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
25.02 20:49:52 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:49:52 [Server] INFO ... 14 more
25.02 20:49:52 [Connect] User Corniival, IP 173.20.117.155
25.02 20:49:52 [Multicraft] Corniival ran command Message of the Day
25.02 20:50:01 [Server] ERROR null
25.02 20:50:01 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin Caeda_Engine v1.1
25.02 20:50:01 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
25.02 20:50:01 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
25.02 20:50:01 [Server] INFO Caused by: java.lang.NullPointerException
25.02 20:50:01 [Server] INFO at com.dyllansplugins.caeda.engine.commands.Chat.onCommand(Chat.java:31) ~[?:?]
25.02 20:50:01 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
25.02 20:50:01 [Server] INFO ... 15 more

**Comment by McCrearyD** [comment]
ac089f260d79c5b30277a91c78e66187b3203264 - key/value pairs in back-end to no longer use commas as separators.
