### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by aerysaegis** [McCrearyD/Caeda_Engine#3]
27.02 02:38:03 [Server] WARN [Caeda_Engine] Server not running at normal efficiency. Please contact a developer.
27.02 02:38:03 [Server] WARN [Caeda_Engine] Server not running at normal efficiency. Please contact a developer.
27.02 02:38:03 [Server] WARN [Caeda_Engine] Server not running at normal efficiency. Please contact a developer.
27.02 02:38:03 [Server] WARN [Caeda_Engine] Server not running at normal efficiency. Please contact a developer.
27.02 02:38:03 [Server] WARN [Caeda_Engine] Server not running at normal efficiency. Please contact a developer.
27.02 02:38:03 [Server] WARN [Caeda_Engine] Server not running at normal efficiency. Please contact a developer.
27.02 02:39:02 [Server] INFO default: AerysAegis
27.02 02:40:08 [Server] INFO Unknown says "Test"
27.02 02:40:08 [Server] ERROR Could not pass event AsyncPlayerChatEvent to Caeda_Engine v1.1
27.02 02:40:08 [Server] INFO org.bukkit.event.EventException
27.02 02:40:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
27.02 02:40:08 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
27.02 02:40:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
27.02 02:40:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
27.02 02:40:08 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1276) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
27.02 02:40:08 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
27.02 02:40:08 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
27.02 02:40:08 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
27.02 02:40:08 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
27.02 02:40:08 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
27.02 02:40:08 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
27.02 02:40:08 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
27.02 02:40:08 [Server] INFO Caused by: java.lang.NullPointerException
27.02 02:40:08 [Server] INFO at com.dyllansplugins.caeda.engine.chat.ChatUtils.sendLocalMessage(ChatUtils.java:133) ~[?:?]
27.02 02:40:08 [Server] INFO at com.dyllansplugins.caeda.engine.chat.ChatUtils.sendLocalMessage(ChatUtils.java:145) ~[?:?]
27.02 02:40:08 [Server] INFO at com.dyllansplugins.caeda.engine.events.ChatListener.onChat(ChatListener.java:49) ~[?:?]
27.02 02:40:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
27.02 02:40:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
27.02 02:40:08 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
27.02 02:40:08 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
27.02 02:40:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
27.02 02:40:08 [Server] INFO ... 11 more

**Comment by McCrearyD** [comment]
Language configuration error
