### ISSUE TITLE
Player inventory deletion

### ISSUE THREAD

**Issue by aerysaegis** [McCrearyD/Caeda_Engine#7]
Players are losing inventory upon switching from one card to the other. i.e, player loses inventory when switching from card 1 to card 2 then back to card 1

**Comment by McCrearyD** [comment]
> player loses inventory when switching from card 1 to card 2 then back to card 1

Player's only lose inventory data when creating new cards, otherwise inventory switching works.

**Comment by McCrearyD** [comment]
fixed in commit 601f65c
